version: '3.9'

services:
  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: always

  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - fastapi
    restart: always
